# Generated by Django 4.0.5 on 2022-06-25 22:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anticipation_status', models.IntegerField(choices=[(1, 'Available'), (2, 'Waiting confirmation'), (3, 'Anticipated'), (4, 'Unavailable'), (5, 'Denied')])),
                ('issuance_date', models.DateTimeField(auto_now_add=True, verbose_name='issuance date')),
                ('anticipation_due_date', models.DateTimeField(blank=True, null=True, verbose_name='pending anticipation due date')),
                ('due_date', models.DateTimeField(verbose_name='due date')),
                ('original_value', models.DecimalField(decimal_places=2, max_digits=11, verbose_name='original value')),
            ],
            options={
                'verbose_name': 'payment',
                'verbose_name_plural': 'payments',
                'default_permissions': [],
            },
        ),
        migrations.CreateModel(
            name='PaymentHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('history_type', models.CharField(choices=[('I', 'Inclusion'), ('A', 'Alteration')], max_length=2, verbose_name='history type')),
                ('history_description', models.CharField(max_length=800, verbose_name='history description')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='date')),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='payment_history', to='payment.payment', verbose_name='payment')),
            ],
            options={
                'verbose_name': 'payment history',
                'verbose_name_plural': 'payment histories',
                'default_permissions': [],
            },
        ),
    ]
