# Generated by Django 4.0.5 on 2022-06-26 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='new_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=11, null=True, verbose_name='new value'),
        ),
    ]
